services:
  backend:
    build:
      context: ./backend
    volumes:
      - ./backend:/app  # Mount code directly; prevent unnecesary container rebuilding 
    ports:
      - "5000:5000"
    env_file:
      - ./backend/.env
    depends_on:
      - db
    networks:
      - webnet

  frontend:
    build:
      context: ./frontend
    volumes:
      - ./frontend:/app
    depends_on:
      - backend
    networks:
      - webnet
  
  db:
    image: mysql:latest
    container_name: mysql
    ports:
      - "3306:3306"
    env_file:
      - ./backend/.env
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - webnet

  nginx:
    build:
      context: .
      dockerfile: Dockerfile.nginx
    ports:
      - "80:80"
    depends_on:
      - frontend
      - backend
    networks:
      - webnet

networks:
  webnet:

volumes:
  db_data:


